from pygame import Color

# Rendering
FRAMES_PER_SECOND = 24

# Measure
SIDE = 64
FONT_SIZE = SIDE // 3
HALF = SIDE // 2
PAD = SIDE // 8
ACTION_AREA = (SIDE * 10, SIDE * 6)
MARGIN = int(SIDE * 2)
CANVAS_AREA = (
    MARGIN + ACTION_AREA[0] + MARGIN,
    MARGIN + ACTION_AREA[1] + MARGIN,
)

DISPLAY_MARGIN = HALF // 2
DISPLAY_AREA = (
    DISPLAY_MARGIN + ACTION_AREA[0] + DISPLAY_MARGIN,
    DISPLAY_MARGIN + ACTION_AREA[1] + DISPLAY_MARGIN,
)
CANVAS_TO_DISPLAY_OFFSET = (DISPLAY_MARGIN - MARGIN, DISPLAY_MARGIN - MARGIN)

OBSERVATION_INPUT_SIDE = SIDE * 2
OBSERVATION_INPUT_AREA = (OBSERVATION_INPUT_SIDE, OBSERVATION_INPUT_SIDE)
OBSERVATION_DOWNSCALE_RATIO = 1
OBSERVATION_OUTPUT_AREA = (
    OBSERVATION_INPUT_AREA[0] * OBSERVATION_DOWNSCALE_RATIO,
    OBSERVATION_INPUT_AREA[1] * OBSERVATION_DOWNSCALE_RATIO,
)

# Objects
CAR_LENGTH = PAD * 2
CAR_WIDTH = PAD
CAR_MIN_TURN = -2
CAR_MAX_TURN = 2
CAR_MIN_SPEED = 0
CAR_MAX_SPEED = 2
CAR_TURN_DEGREES_PER_FRAME = 3
CAR_SPEED_PIXELS_PER_FRAME = 1

# Colors
BLACK = Color(0, 0, 0)
LIGHT_BLACK = Color(50, 50, 50)
WHITE = Color(255, 255, 255)
GREEN = Color(0, 128, 0)
DARK_GREEN = Color(0, 100, 0)
DARK_GRAY = Color(100, 100, 100)
DARKEST_GRAY = Color(80, 80, 80)
GRAY = Color(128, 128, 128)
LIGHT_GRAY = Color(145, 145, 145)
LIGHTEST_GRAY = Color(180, 180, 180)
YELLOW = Color(255, 255, 0)
BLUE = Color(30, 144, 255)
RED = Color(232, 33, 39)
CENTERLINE = Color(255, 153, 0)
TURN_SIGNAL = Color(255, 219, 56)

COLOR_KEY = Color(255, 192, 203)

# Configurations
ROAD_MAP = [
    "  ┌─┐ ┌┐  ",
    "  │ └─┘└┐ ",
    "  │     └┐",
    "┌─┼──┬───┘",
    "│ │  │   ",
    "└─┴──┘   ",
]
